### ISSUE TITLE
Problem with fuse?

### ISSUE THREAD

**Issue by Trevoke** [ianpreston/redditfs#2]
Wow look a these errors

$ python redditfs.py /r
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in __call__
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in **call**
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in __call__
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in **call**
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in __call__
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in **call**
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in __call__
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in **call**
    return getattr(self, op)(_args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
Traceback (most recent call last):
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 414, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 422, in getattr
    return self.fgetattr(path, buf, None)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 668, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/fuse.py", line 709, in __call__
    return getattr(self, op)(*args)
  File "redditfs.py", line 32, in getattr
    f = self._traverse(path)
  File "redditfs.py", line 70, in _traverse
    return self._populate_subreddit(fn.lower())
  File "redditfs.py", line 81, in _populate_subreddit
    r.raise_for_status()
  File "/Users/agiacomoni/devel/redditfs/env/lib/python2.7/site-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

**Comment by Miladiir** [comment]
This is because there is no URL such as [http://reddit.com/r/](http://reddit.com/r/) 404s aswell. As soon as you type in ls /r/yourSubbredditNameHere/ you don't get the error anymore. You need to ls a subreddit first to get it show up in Finder on Mac. After that you can access the 3 files in each post.

**Comment by Trevoke** [comment]
So I start your script, I get all these errors, but then I can go to another terminal and do `ls` and browse reddit. Fair enough, I suppose. I'd still rather not get these errors.

**Comment by Miladiir** [comment]
It's not my script nor my repository, I am just kind enough to help you out my friend ^^ But you're right. Instead of the default link with the url I posted earlier, it should link with the frontpage or something to not generate 400 lines of traceback.

**Comment by ianpreston** [comment]
Your OS is requesting subdirectories which are not valid subreddits. Cleaning up the log output (esp. for trivial errors  like these 404s) is definitely on the todo list.
